        // Dados completos dos ensaios
        // Nome da igreja;Cidade;Dia do Ensaio;Hora do Ensaio;Endereco Google maps;Setor;Nome Encarregado Local;Nome Encarregado Regional;Meses T=Todos, I=ímpares, P=Pares, 3M1=JAN/ABR/JUL/OUT, 3M2=FEV/MAI/AGO/NOV, 3M3=MAR/JUN/SET/DEZ 
        const dados = [
            "<B>Central</B>;<B>Aragoiânia</B>;1º DOMINGO;<B>T</B>;FAkanFsUT93mmLiu8;6;Marcos Ferreira;;T",
            "Vila Brasília;Aparecida;1º DOMINGO;T;xYJT4GTg7hSCEzDx6;6;Marcos Batista;;T",
            "<B>Setor Garavelo</B>;<B>Aparecida</B>;1º DOMINGO;<B>T</B>;cbaHom1Dz6uJrsG39;6;Alex Flávio;Claudio Pontes;T",
            "Setor dos Bandeirantes;Aparecida;1º DOMINGO;T;8NjPZFBb4FvHgnj18;6;Edimundo Rodrigues;;T",
            "Residencial Village Garavelo;Aparecida;1º DOMINGO;T;d5ArP8Dez9qpoGqt7;6;Ezechias;;T",
            "Jardim Tiradentes I;Aparecida;1º DOMINGO;T;EqvstVAQsBkc6Ybh8;6;Edneide Jesus;;T",
            "Jardim Casa Grande;Aparecida;1º DOMINGO;T;N6TzmdWUVKmjq7qU9;6;Gustavo Rodrigo;;T",
            "Bairro Independência;Aparecida;1º DOMINGO;T;d58NBSKruwc735pA9;6;Roberto Santana;Odário;T",
            "Vila São José;Goiânia;1º DOMINGO;T;5kdjpLgQreAGofYKA;5;;;T",
            "Setor Universitário;Goiânia;1º DOMINGO;T;f4jkwB9HdBhJMobN6;1;;;T",
            "Setor Urias Magalhães;Goiânia;1º DOMINGO;T;fYH4domMCTcszBZc7;5;Josafá Silveira;Doralino;T",
            "Setor Norte Ferroviário II;Goiânia;1º DOMINGO;T;fyt967DQ1EgXkji18;5;;;T",
            "Setor Madre Germana 2;Goiânia;1º DOMINGO;T;JfvWA4JTasNrqzTo9;2;Welliton;André;T",
            "Setor Faiçalville;Goiânia;1º DOMINGO;T;BnQwHq2mhdCuNmsf7;2;Josimar;Huiwerson;T",
            "Setor Bela Vista;Goiânia;1º DOMINGO;T;6FfuP1QrYMLrrHXm8;1;;;T",
            "Setor Coimbra;Goiânia;1º DOMINGO;T;AHA4PNhtdDhWqMP76;4;Euzébio Marcelino;Davi Borges;T",
            "Setor Alphaville II;Goiânia;1º DOMINGO;T;VJfWLbqyQPxEaRhm6;3;;;T",
            "Residencial Itaipu;Goiânia;1º DOMINGO;T;meFED6rqGuhwh9pE7;2;;;T",
            "Residencial Brisas da Mata;Goiânia;1º DOMINGO;T;MvRbJroWVEVyQyo3A;4;Lourenço de Sousa;Túlio Marcos;T",
            "Parque Tremendão;Goiânia;1º DOMINGO;T;g8YtWxosoERd1aRJ6;4;Ferdinan Gomes;Túlio Marcos;T",
            "Parque Industrial João Braz;Goiânia;1º DOMINGO;T;YuLEdrUSCdYVVmHH9;3;;;T",
            "Jardim Presidente;Goiânia;1º DOMINGO;T;rfvBKbu67ozUQNta9;2;José Eduardo;Hiwerson/Pedro Pimenta;T",
            "Jardim Nova Esperança;Goiânia;1º DOMINGO;T;Y1sZAuF7Td5gjHtUA;3;;;T",
            "Jardim Liberdade;Goiânia;1º DOMINGO;T;8jnsTy5LySrqKVzP7;4;Carlos de Souza;Davi Borges;T",
            "Jardim Guanabara;Goiânia;1º DOMINGO;T;TAjbgKfYSEVyUPVr5;5;;;T",
            "Jardim América;Goiânia;1º DOMINGO;T;aFi4SSMVq3qz5bsh8;2;Moacir;André;T",
            "<B>Guapó - Central</B>;<B>Guapó</B>;1º DOMINGO;<B>T</B>;UmoNQHrabx42qfyM7;7;;;T",
            "<B>Abadia de GoiáS - Central</B>;<B>Abadia</B>;1º DOMINGO;<B>T</B>;TgHBjRy7r7cwX2up8;7;;;T",
            "Carolina Parque;Goiânia;1º DOMINGO;T;eJzMbXYnWATf43Vy5;3;;;T",
            "<B>Vila Bom Sucesso-Central</B>;<B>Senador Canedo</B>;1º DOMINGO;<B>T</B>;qUWszvKWJqabt2aX8;8;;;T",
            "Vila São Sebastião;Senador Canedo;1º DOMINGO;T;MZuF2s6tX4RwZ7sX7;8;;;T",
            "<B>Bela Vista - Central</B>;<B>Bela Vista</B>;1º DOMINGO;<B>T</B>;W3w9b6q1KSC1iPdN6;8;;;T",
            "Jardim das Oliveiras;Senador Canedo;1º DOMINGO;T;kZ3a1w8SaeHBRkcE9;8;;;T",
            "Parque Alvorada;Senador Canedo;1º DOMINGO;T;cB2KSg7McQrJAiwm6;8;;;T",
            "Papillon Parque;Aparecida;1ª SEGUNDA-FEIRA;N;YCroEDoHWJp4mBq59;6;Daniel Pedrosa;Thiaguinho;T",
            "Cidade Vera Cruz II;Aparecida;1ª SEGUNDA-FEIRA;N;fJiiuLUyTgePVdoRA;3;Cleiton;;T",
            "Colina Azul II;Aparecida;1ª SEGUNDA-FEIRA;N;nE1oznfqzcFHZNNv8;6;Joel Soares;;T",
            "Serra Azul;Goiânia;1ª SEGUNDA-FEIRA;N;b6RKsb7ZjbWLZsyeA;3;;;T",
            "Residencial Recanto do Bosque;Goiânia;1ª SEGUNDA-FEIRA;N;beu4rSFcierdzrTL7;4;Martim Pinto;Jackson;T",
            "Residencial Junqueira;Goiânia;1ª SEGUNDA-FEIRA;N;jg68McQ7giL62ba28;3;;;T",
            "Jardim Mariliza;Goiânia;1ª SEGUNDA-FEIRA;N;k81iAAmHK7dhhftw8;1;;;T",
            "<B>Goianira - Centrl</B>;<B>Goianira</B>;1ª SEGUNDA-FEIRA;<B>N</B>;DaKwLA4yfFB9uvxC8;7;;;T",
            "Bairro São Carlos;Goiânia;1ª SEGUNDA-FEIRA;N;WrzELsFVxh1oyZJi6;4;Cláudio Antônio;Jackson;T",
            "Residencial Vitta;Hidrolândia;1ª SEGUNDA-FEIRA;N;gLXPAYV8PmwvJbiM8;6;Francisco Letício;;3M2",
            "Central (Nazaré);Hidrolândia;1ª SEGUNDA-FEIRA;N;o41TdVY6kpwAdJoF8;6;Francisco Jocerlandio;;3M3",
            "Chácara Savana;Hidrolândia;1ª SEGUNDA-FEIRA;N;naghoBxUC2qv6M5e8;6;;;3M1",
            "Cidade Jardim;Goiânia;1ª TERÇA-FEIRA;N;h7aTYPFAnBYe6W427;3;;;T",
            "Parque Oeste Industrial;Goiânia;1ª TERÇA-FEIRA;N;yFEJsMV1oq5Lo7BK8;3;;;T",
            "Parque Atheneu;Goiânia;1ª QUARTA-FEIRA;N;6JJ8NsTNgakSJVTV7;1;;;T",
            "Vila Rizzo;Goiânia;1ª QUINTA-FEIRA;N;eNNv5dgHFbinBLL47;3;Aremi;Nereu;T",
            "Residencial Center Ville;Goiânia;1ª QUINTA-FEIRA;N;QfcbSL2by3fQi45TA;2;;;T",
            "Jardim Santo Antônio;Goiânia;1ª QUINTA-FEIRA;N;JBvHtFB7vJAK4aC8A;2;Cleibe;André;T",
            "Jardim Balneário Meia Ponte;Goiânia;1ª SEXTA-FEIRA;N;C5erC5BGabA7aH8H7;4;Benedito Valério;Túlio Marcos;T",
            "Parque Ibirapuera;Aparecida;1ª SEXTA-FEIRA;N;YBz12uTTvvupg1v16;6;Lucas de Jesus;;T",
            "Varjão - Faz Salobro de Baixo;Varjão;1ª SEXTA-FEIRA;N;WedDouD7xqsoosXD8;7;;;T",
            "Independência Mansões I;Aparecida;1ª SEXTA-FEIRA;N;HB5VegSFgms4WMGj7;6;Ricardo campelo;;T",
            "Residencial Mar Del Plata;Goiânia;1ª SEXTA-FEIRA;N;KL3hP3EnU6FFn7Em6;1;André Lisboa;Ricardo Rosemberg;T",
            "Santo Hilário;Goiânia;1ª SEXTA-FEIRA;N;ofo9X9vxfmm6zjbo6;1;;;T",
            "Ana Rosa;Trindade;1ª SEXTA-FEIRA;N;MGQt18SFYHxPvpKj8;7;;;T",
            "Vargem Bonita;Senador Canedo;1ª SEXTA-FEIRA;N;x7evhRndRAqxmaWb9;8;;;T",
            "Setor Estrela Dalva;Goiânia;1ª SEXTA-FEIRA;N;DJJ1EU8izHd3iVkh6;4;Jardel Mendes;Jackson;T",
            "Jardim Ipanema;Aparecida;1º SáBADO;T;8gmFtFfCeVx2NvVx7;6;João Evangelista;;T",
            "Setor Perim;Goiânia;1º SáBADO;T;jBCcBz3r4Ko1LF3o7;5;Antonio Lima;;T",
            "Setor Palmito(confirmar);Goiânia;1º SáBADO;T;tM3Z2rcm5XthTGLn6;1;;;T",
            "Setor Goiânia Viva;Goiânia;1º SáBADO;T;KdGCYm1SVy7Qxfqc6;3;;;T",
            "Residencial Morada do Ipê;Goiânia;1º SáBADO;T;GksGsiGsrxWWGYe99;5;;;T",
            "Residencial Íris Ville;Goiânia;1º SáBADO;T;VyEhWKcqUz2NdD5U7;1;;;T",
            "Real Conquista;Goiânia;1º SáBADO;N;T3PugKZyNpHAMAg56;2;Adriel;Pedro Pimenta;T",
            "Parque das Flores;Goiânia;1º SáBADO;T;MuWhXkmKDwNGgEXh8;4;Cícero Vicente;Davi Borges;T",
            "Chácara Céu Azul;Goiânia;1º SáBADO;T;Z6jVPKW89bh8zWHc8;4;Ivon Ribeiro;Davi Borges;T",
            "Distrito de Nova Fátima;Hidrolândia;2º DOMINGO;T;Jitgq66ePpp4BaLK8;6;Márcio Souza;;T",
            "Setor Vale do Sol;Aparecida;2º DOMINGO;T;zJzwGSJbX4NTYQAe8;6;Samuel Jefferson;;T",
            "Setor Serra Dourada III;Aparecida;2º DOMINGO;T;WYJtMZjDUu5pUgLx7;6;Chales Anderso;;T",
            "Setor Marista Sul;Aparecida;2º DOMINGO;T;pJatAUUpBst8VipH8;6;Wenderson;;T",
            "Residencial Caraíbas;Aparecida;2º DOMINGO;T;KuwxTZAzTQ57avH67;6;Marcos Bezerra;;T",
            "Residencial Santa Luzia;Aparecida;2º DOMINGO;T;Hfbyg7kU1orKdBJ8A;6;Joel Aminadabe;;T",
            "Rosa dos Ventos;Aparecida;2º DOMINGO;T;t5fpJLTsZcZa7too7;6;;;T",
            "Jardim das Cascatas;Aparecida;2º DOMINGO;T;c88qH1kAHEnyCLV7A;6;Júnior César;;T",
            "Cidade Vera Cruz I;Aparecida;2º DOMINGO;T;8z925WBJfg1RC2oE6;6;Helington Lima;;T",
            "Vila Santa Helena;Goiânia;2º DOMINGO;T;8bbzMas2TnnVDXNy8;5;Dinilson Bernardes;Doralino;T",
            "Vila Pedroso;Goiânia;2º DOMINGO;T;H7qLWAEgHB1G2udx7;1;;;T",
            "Setor Jaó;Goiânia;2º DOMINGO;T;TNb2ePXS5rQuxJx26;5;;;T",
            "Setor Nordeste;Goiânia;2º DOMINGO;T;JdMpUusT9jvbXuAY9;3;;;T",
            "Setor Finsocial;Goiânia;2º DOMINGO;T;LhYD3ZknK7MNH1tXA;4;;Túlio Marcos;T",
            "Setor Alto do Vale;Goiânia;2º DOMINGO;T;qPrJpePnWe5WCLh6A;4;Tiago;Túlio Marcos;T",
            "Jardim Pompéia;Goiânia;2º DOMINGO;T;W3koKo4c4GdPf9VPA;5;;;T",
            "Jardim Itaipu;Goiânia;2º DOMINGO;T;MQnbKAhq1fcgPSxdA;2;Anderson/Josemir;Pedro Pimenta;T",
            "Jardim das Oliveiras;Goiânia;2º DOMINGO;T;kqZLW4r7Qce2jqze9;3;Cleiber José;Humberto;T",
            "Jardim Curitiba III;Goiânia;2º DOMINGO;T;NPx2UipgVr8f7NtD9;4;Cloves de Souza;Jackson;T",
            "Goianira - Cora Coralina;Goianira;2º DOMINGO;T;eJH1spFKgCKxmA6t5;7;;;T",
            "Conj Vera Cruz II;Goiânia;2º DOMINGO;T;NqdAXaUcVfFszREh8;3;Ítallo;José Humberto;T",
            "Abadia de Goiás - Rec dos Dourados;Abadia;2º DOMINGO;T;mN3ME7NYVVikaa2u5;7;;;T",
            "Jardim dos Buritis;Aparecida;2ª SEGUNDA-FEIRA;N;TayGSqjSSEow244m8;6;Osires Elias;;T",
            "Setor Criméia Leste;Goiânia;2ª SEGUNDA-FEIRA;N;BpjzdrtJ2dDbwLjKA;5;;;T",
            "Goianira - Parque Los Angeles I;Goianira;2ª SEGUNDA-FEIRA;N;nGUY8PSRHYXz8qJ67;7;;;T",
            "Capuava;Goiânia;2ª SEGUNDA-FEIRA;N;VSSC4zA2MYhZCbm26;3;;;T",
            "Vila Rosa;Goiânia;2ª TERÇA-FEIRA;N;1cFS7ezbQ3qPUWDy7;2;Joilson;Isaque;T",
            "Residencial Fonte das Águas;Goiânia;2ª TERÇA-FEIRA;N;aVP46SN2a81qnUxz6;4;Acrício Vieira;Davi Borges;T",
            "Fama - Setor Marechal Rondon;Goiânia;2ª TERÇA-FEIRA;N;5TyhAmrtwvYnvwfw8;5;;;T",
            "Jardim Itapuã;Aparecida;2ª TERÇA-FEIRA;N;MEfkGCz8dp56TEL79;6;Mizael Balduíno;;T",
            "Parque Flamboyant;Aparecida;2ª QUARTA-FEIRA;N;p1cv8v1pXmtsUyiq8;6;Gideon;;T",
            "Vila Roriz - Urias Magalhães 2;Goiânia;2ª QUARTA-FEIRA;N;YwXrcBbGEWvqpZb87;5;;;T",
            "Setor São Judas Tadeu;Goiânia;2ª QUARTA-FEIRA;N;z7SA5X6QjFSF47D89;5;;;T",
            "Setor Santa Genoveva;Goiânia;2ª QUARTA-FEIRA;N;uYp9wBLFHeQJf1rWA;5;;;T",
            "Jardim Novo Mundo;Goiânia;2ª QUARTA-FEIRA;N;t193qgTKffUqQhDF7;1;;;T",
            "Jardim Paraíso;Aparecida;2ª QUINTA-FEIRA;N;3ur2XR6PRtxYagc3A;6;Assis Leandro;;T",
            "Jardim Alto Paraíso I;Aparecida;2ª QUINTA-FEIRA;N;836KUbCkUmW9m7HAA;6;Johnathan;;T",
            "Residencial Rio Verde;Goiânia;2ª QUINTA-FEIRA;N;ABiGL9zxsG7KbcMe7;3;;;T",
            "Jardim Goiás;Goiânia;2ª QUINTA-FEIRA;N;BbRcFyWtZLCqiRV16;1;;;T",
            "Jardim Caravelas;Goiânia;2ª QUINTA-FEIRA;N;5MavwLrtVk6pbALm8;2;Waldir;Jackson;T",
            "Cond das Esmeraldas;Goiânia;2ª QUINTA-FEIRA;N;ZPVuUDLGJwsHp6jz5;2;Gustavo Ferraz;Jackson;T",
            "<B>Jardim Europa</B>;<B>Goiânia</B>;2ª QUINTA-FEIRA;<B>N</B>;wCXzwnDgT28jsN6B9;2;Pedro Machado;Hiwerson;T",
            "Setor Expansul;Aparecida;2ª SEXTA-FEIRA;N;fo5Eb6Vat9R4oTGe8;6;Tulio Gustavo;;T",
            "Parque Hayala;Aparecida;2ª SEXTA-FEIRA;N;HdfXFEG8f7UbEpTXA;6;Wilian Gonçalves;;T",
            "Jardim Dom Bosco II;Aparecida;2ª SEXTA-FEIRA;N;SgRsvHqwLqXTX7HV6;6;Elias Barbosa;;T",
            "Setor Grajaú;Goiânia;2ª SEXTA-FEIRA;N;Z83wxgptUs3CpVGX6;2;Marcos;Huiwerson;T",
            "Setor Pedro Ludovico;Goiânia;2ª SEXTA-FEIRA;N;SgUPyCuxBkm485Wi7;1;;;T",
            "Setor Santos Dumont;Goiânia;2ª SEXTA-FEIRA;N;vJXpG8Z6akbmuHwQ9;3;;;T",
            "Residencial Buena Vista III;Goiânia;2ª SEXTA-FEIRA;N;fWnMGPmvaCyj5tR78;3;;;T",
            "Parque Amazônia;Goiânia;2ª SEXTA-FEIRA;N;uz5JdYhjKTGDtxNLA;2;Lynardo;Isaque/André/Jackson;T",
            "Jardim das Aroeiras / Vila Concórdia;Goiânia;2ª SEXTA-FEIRA;N;tiL3hV4RD973dsGG6;1;;;T",
            "Eldorado Oeste;Goiânia;2ª SEXTA-FEIRA;N;SuHs1ZRmcLgdekz56;3;;;T",
            "Bairro Goyá;Goiânia;2º DOMINGO;T;cxht1iptcMjbbXEi6;2;Wermerson;Hiwerson;T",
            "Fazenda Cachoeirinha;Aragoiânia;2º SáBADO;T;2c3WhUHpr9oFYQd4A;6;Josephy;;T",
            "Residencial Amim Camargo II;Goiânia;2º SáBADO;T;hewReSMKn7jHxEUq5;2;Luiz Ribeiro;André;T",
            "Setor Tocantins;Aparecida;3º DOMINGO;T;yUevc3XjBBzRxseGA;6;Jean de Macedo;;T",
            "Jardim Tiradentes II;Aparecida;3º DOMINGO;T;qacwwAKCEdfWEZgH7;6;Auriu;Pedro Moreira;T",
            "Jardim Iracema;Aparecida;3º DOMINGO;T;uwDWmt5RK1qaDWbd9;6;Gleidson;;T",
            "Vila Cristina;Goiânia;3º DOMINGO;T;oraHscBHqUFGNJ5a8;4;João Gonçalves;Davi Borges;T",
            "Residencial Solange Parque III;Goiânia;3º DOMINGO;T;grD9H9zX5hc8TJWD8;3;;;T",
            "Residencial Vale dos Sonhos;Goiânia;3º DOMINGO;T;FEUpPPMPR1k337E27;5;;;T",
            "Setor Gentil Meireles;Goiânia;3º DOMINGO;T;THhmWwk9CepizSS6A;5;;;T",
            "Residencial Barra Vento;Goiânia;3º DOMINGO;T;mDHg64SGZM5z1Rd16;4;Santil Tomaz;Túlio Marcos;T",
            "Parque Maracanã;Goiânia;3º DOMINGO;T;CxBqm41inwY99xPz8;4;Marcelo Mello;Davi Borges;T",
            "Privê das Oliveiras;Goiânia;3º DOMINGO;T;DJD9PxZ3N6uWYSvy5;2;Bruno Rodrigues;André;T",
            "Água Branca;Goiânia;3º DOMINGO;T;2YothebbxUbFvadD6;1;;;T",
            "Bairro Floresta;Goiânia;3º DOMINGO;T;5jMca7ZaDZzQ5ZMc8;4;Edjam Divino;Jackson;T",
            "Vila João Vaz;Goiânia;3ª SEGUNDA-FEIRA;N;Q3j61hDhWYLYythDA;3;;;T",
            "Goianira - Jardim das Paineiras;Goianira;3ª SEGUNDA-FEIRA;N;sGNQWhUMzD1vkNSx7;7;;;T",
            "Residencial Orlando Morais;Goiânia;3ª SEGUNDA-FEIRA;N;erGUcf8GdNsG1cHh9;5;;;T",
            "Parque Anhanguera;Goiânia;3ª TERÇA-FEIRA;N;Y6jCNpoXMtKf4hrM9;2;Isaías;Isaque;T",
            "Vila Viana;Goiânia;3ª QUARTA-FEIRA;N;Ytm6KEcX6VvFA3sp9;1;;;T",
            "Jardim da Luz;Goiânia;3ª QUARTA-FEIRA;N;KDBznngerzpQ34NW8;1;;;T",
            "Chácara Mansões do Campus;Goiânia;3ª QUINTA-FEIRA;N;oaLJPkjuidTaVXS17;5;;;T",
            "Parque São Jorge;Aparecida;3ª QUINTA-FEIRA;N;2YEbMbcrhrDXXVza6;6;Emerson Noleto;;T",
            "Setor Pontal Sul II;Aparecida;3ª SEXTA-FEIRA;N;XX6ErRQMTNx4UQQS9;6;Jocirono Bispo;;T",
            "Indepedência Mansões II;Aparecida;3ª SEXTA-FEIRA;N;gidwYzPgTvZ5b31Y9;6;Ismael;;T",
            "<B>Varjão - Central</B>;<B>Varjão</B>;3ª SEXTA-FEIRA;<B>N</B>;wePyJHKwj3dns28M7;7;;;T",
            "Vila Itatiaia;Goiânia;3ª SEXTA-FEIRA;N;hgVm1kTF3Zv93XtJ7;5;;;T",
            "Cruzeiro do Sul;Aparecida;3ª SEXTA-FEIRA;N;iCpCaCbwqBV2vAVG8;6;Gildemar;;T",
            "Recanto das Minas Gerais;Goiânia;3ª SEXTA-FEIRA;N;E9GE2mEnjtiPRuHA8;1;;;T",
            "Residencial Campos Dourados;Goiânia;3ª SEXTA-FEIRA;N;RWjhyBhNg4SVaCrE9;2;Anselmo;Jackson;T",
            "Chão de Eestrelas;Aragoiânia;3ª SEXTA-FEIRA;N;Z9psCkC3UPfagmZFA;6;Saulo Nogueira;;T",
            "Garavelo Sul II;Hidrolândia;3º SáBADO;T;LoWB7rwcnvpwq5JAA;6;;;T",
            "SíTIO SANTA LUZIA;Aparecida;4º DOMINGO;T;6D1j23eCkntw7UFA6;6;Isaias dos Santos;;T",
            "Jardim Boa Esperança;Aparecida;4º DOMINGO;T;ofG7hB6yQgk9zG6h8;6;Neilton;;T",
            "Setor Goiânia II;Goiânia;4º DOMINGO;T;pkzUdw3q6PgeTebX7;5;;;T",
            "Jardim Colorado;Goiânia;4º DOMINGO;T;5nuz13naXNwcWoCZ7;4;Baltazar Dias;Túlio Marcos;T",
            "Jardim Curitiba I;Goiânia;4º DOMINGO;T;q2HGHxpSGALNVxhMA;4;Marcio Mendes;Jackson;T",
            "Jardim dos Cerrados III;Goiânia;4º DOMINGO;T;GFbqCarL74kEfejc7;3;;;T",
            "Residencial Felicidade;Goiânia;4º DOMINGO;T;6JDkDNa2fx9bwthh8;5;;;T",
            "Mansões Paraíso;Aparecida;4ª SEGUNDA-FEIRA;N;4dKHXjHzNevLrX538;6;Leonardo da Silva;;T",
            "Jardim Bonança;Aparecida;4ª SEGUNDA-FEIRA;N;rLyFkSvWcfL5TmM1A;6;José Marcelo;;T",
            "Jardim Buriti Sereno Garden;Aparecida;4ª SEGUNDA-FEIRA;N;TscgNASVCBuEjnBA8;6;Valdeir;;T",
            "Goianira - Residencial Triunfo;Goianira;4ª SEGUNDA-FEIRA;N;99mL3zFYwHzHGNso8;7;;;T",
            "Goianira - Setor Sul (Jardim Imperial);Goianira;4ª SEGUNDA-FEIRA;N;w3ahx7ZqUy8KeEAJA;7;;;T",
            "Jardim Califórnia;Goiânia;4ª QUINTA-FEIRA;N;PqrrW6zSdiD1RSKs8;1;;;T",
            "Residencial Park Solar;Goiânia;4ª SEXTA-FEIRA;N;sfcXgF2igCY2nsRG6;4;Edenilson Noé;Jackson;T",
            "Santa Rita;Goiânia;4ª SEXTA-FEIRA;N;GyvMHiMhQvVfo6uC6;2;Wesley;Hiwerson;T",
            "Distrito de Oloana;Hidrolândia;4º SáBADO;T;Bm6uW1fF3p9qvXsUA;6;;;T",
            "Jardim Primavera;Goiânia;4º SáBADO;T;V2PJyKFW5SEewXrf8;4;Luis Romário;Davi Borges;T",
            "Vila Delfiori;Aparecida;2º SáBADO;T;7YpA5szLBfYUbNFc9;6;José Batista;;I",
            "Setor Madre Germana I;Aparecida;3º DOMINGO;T;BKSiqBPMvngATgkP8;6;Francys Carlos;;3M2",
            "Jardim dos Ipês I;Aparecida;3º DOMINGO;T;tXtR21baRaCyFiHG6;6;Wesley de Jesus;;3M3",
            "Jardim dos Ipês II;Aparecida;3º DOMINGO;T;MXJiuPGyAUtKCLaAA;6;Elias;;3M1",
            "Jardim Dom Bosco I;Aparecida;5º DOMINGO;T;P5fCZqCEhJQ8iM8B6;6;Eleone;;T",
            "Jardim Ipiranga;Aparecida;5ª SEXTA-FEIRA;N;d6PEBRnhFiwiBrPw7;6;Juscélio;;T",
            "Jardim Helvécia;Aparecida;3ª SEGUNDA-FEIRA;N;vvzTZ4gNRCtqVaU97;6;Ney;Thiaguinho;P",
            "Guapó - Cidade Nova;Guapó;3ª SEGUNDA-FEIRA;N;V8nFr4CRJMs78NVc8;7;;;P",
            "Guapó - Vila João Pedro;Guapó;3ª SEGUNDA-FEIRA;N;GMFbPuVZB5a8cHGG7;7;;;I",
            "Cardoso II;Aparecida;3ª SEGUNDA-FEIRA;N;HcPzsYCXyMEx3XpQA;6;Wesley;;I",
            "Campos Dourados;Aragoiânia;1º SáBADO;T;x3P79L7ZvybRpbyW7;6;Rogério Almeida;;I",
            "Posselândia - Central;Guapó;2ª SEGUNDA-FEIRA;N;Vrxw18rXRe5oeaYT6;7;;;I",
            "Parque Veiga Jardim II;Aparecida;2ª SEXTA-FEIRA;N;2RgB2GJw237amEYL8;6;Ezequiel Gonçalves;Ordário Benedito;I",
            "Distrito Vila Rica;Goiânia;3ª SEXTA-FEIRA;N;kRnnufBAuWN2HiedA;5;;;I",
            "Ind Setor Antônio (T Prometida);Aparecida;2ª SEXTA-FEIRA;N;TvaUyyRADcfky5eaA;6;Agnaldo;Ordario Benedito;P",
            "Jardim Buriti Sereno I;Aparecida;4ª SEGUNDA-FEIRA;N;Zdk6Tqvsp9oZsavS7;6;Wanderson;;I",
            "Nova Olinda;Aparecida;4º DOMINGO;N;LZcYBBYJ4qhgPJ9U9;6;Lucas;Luciano;T",
            "Setor Aeroporto Sul;Aparecida;5º DOMINGO;T;kJnN5yAhCJAfm9gd9;6;Leonel Rodrigues;;T",
            //"Setor Continental;Aparecida;;wnMvCcxyCGSxrWD89;6;;;T",
            //"Distrito de Santa Maria;Hidrolândia;;6;;;T",
            "Jardim Alto Paraíso II;Aparecida;2ª QUARTA-FEIRA;N;c8kRiGzwVfpy43yPA;6;Eliezer;Pedro Moreira;T",
            "Pontakaiana;Trindade;2ª SEXTA-FEIRA;N;g5JM3crwXzVCd1GY9;7;Wanderllon da Silva;Uaslei Ribeiro;T",
            "Jardim Imperial II - Dª Ires II;Trindade;2º SáBADO;T;bTQiPYLCFB4wwYzm9;7;;;T",
            "Setor Palmares - Maysa II;Trindade;2º DOMINGO;T;kz32ghcwk65SdK1k8;7;;;T",
            "<B>Central - Vila Pai Eterno</B>;<B>Trindade</B>;2ª SEGUNDA-FEIRA;<B>N</B>;XXYM45ajGVQu1Rsn6;7;;;T",
            "Jardim Califórnia;Trindade;2ª QUARTA-FEIRA;N;xn9oBpk1WRfyq4s88;7;;;3M2",
            "Alto do Cerrado I;Trindade;3º SáBADO;T;eTCkDsAjQoiGZUhS9;7;Jonathan;Uaslei Ribeiro;T",
            "Laguna Park - Campestre;Trindade;3º DOMINGO;T;G2FRfvxcDfnQfKvJ8;7;;;T",
            "Residencial Vieira;Trindade;3ª SEGUNDA-FEIRA;N;su4KnXzBMVFvt2VT7;7;;;T",
            "Maysa I;Trindade;3ª TERÇA-FEIRA;N;BPjCP9Z1ou6XWuJb7;7;;;T",
            "Jardim Marista;Trindade;4º SáBADO;T;RTcfjfJqgSwfY7Gr7;7;;;T",
            "Decolores;Trindade;4º DOMINGO;T;abZFKGwXJHVcpjy37;7;;;T",
            "Santa Bárbara;Trindade;4º DOMINGO;T;;7;;;I",
            "Mariápolis;Trindade;5ª SEXTA-FEIRA;N;;7;;;T",
            "Aracy Amaral;Senador Canedo;4ª SEXTA-FEIRA;N;DEXdyFAsmXsc3x4u5;8;;;T",
            "Bairro das Indústrias;Senador Canedo;4º DOMINGO;T;2fhd7R8MG4TfQwjL6;8;;;T",
            "<B>Bonfinópolis</B>;<B>Senador Canedo</B>;2ª SEXTA-FEIRA;<B>N</B>;morZzMHTBz4cuios6;8;;;T",
            "<B>Caldazinha</B>;<B>Caldazinha</B>;4ª SEXTA-FEIRA;<B>N</B>;H11DTsDLBQVYJkaNA;8;;;T",
            "Conjunto Morada Nova;Senador Canedo;4º SáBADO;T;rSFpwgzkdg8Wp3we6;8;;;T",
            "Fazenda Bom Jardim;Caldazinha;2º SáBADO;T;QxGpYiRikZ2eW9cX7;8;;;T",
            "Jardim Canedo I;Senador Canedo;3º SáBADO;T;XGZjH6uoV8urG5jt9;8;;;T",
            "Morada do Morro;Senador Canedo;2ª SEXTA-FEIRA;N;h7ktHfGk2n2mbGFq5;8;;;T",
            "Residencial Boa Vista;Senador Canedo;4ª SEXTA-FEIRA;N;w3LGb9Mt2MG8fRRj9;8;;;T",
            "Residencial Buritis;Senador Canedo;3ª SEXTA-FEIRA;N;xtNaHNaNA3XFWkpJ6;8;;;T",
            "Roselândia;Bela Vista;3º DOMINGO;T;;8;;;T",
            "Santa Edwiges;Senador Canedo;3ª SEXTA-FEIRA;N;spZgKt2EzoCtY7tf9;8;;;T",
            "Vila Mata Feia;Senador Canedo;2ª TERÇA-FEIRA;N;LcpQV3qQMtYBWzk99;8;;;T",
            "Vila Galvão;Senador Canedo;2ª TERÇA-FEIRA;N;mCD5gdLAp37sadDR6;8;;;T",
            "Jardim Primavera;S L Montes Belos;1º SáBADO;T;XB6yH7hTpZVmaKDs8;9;Wallison Klleuver;Jackson;T",
            "Firminópolis;Firminópolis;4º SáBADO;N;Xs9cLn374eSeSXUB9;9;Wesley;Jackson;T",
            "Turvânia;Turvânia;3º SáBADO;T;ur6BTXyHSUmgd9qp9;9;Witian(instrutor);Jackson;T",
            "Paraúna;Paraúna;2º DOMINGO;N;UoqYSPJyvfiMMLUJ6;9;Rogério(instrutor);Jackson;T",
            "Aurilândia;Aurilândia;2º DOMINGO;N;;9;Welberty;Jackson;T",
            "Sanclerlândia;Sanclerlândia;2ª SEXTA-FEIRA;N;NbEm4gPVZrU1H9vB9;9;Leonardo;Jackson;T",
            "Adelândia;Adelândia;5º DOMINGO;T;8WfSCDgYps2rzjFM7;9;Wender Gomes;Jackson;I",
            "Palminópolis;Palminópolis;2º SáBADO;N;DTR9vz7ZECR6Bpqq6;9;João;Jackson;T",
            "Jardim Barcelona;Senador Canedo;3ª TERÇA-FEIRA;N;sBkqgEbx5CxVcsaZ6;8;;;T",
            "CENTRAL;Inhumas;1ª TERÇA-FEIRA;N;AtCDRmyAZfVmcbZP6;10;;;T",
            "TAQUARAL;Taquaral;1º SÁBADO;T;HPudBBd7sQsjMsXJA;10;;;T",
            "SETOR PARAÍSO;Inhumas;2ª TERÇA-FEIRA;N;EefgTofg2UTr2ZTN6;10;;;T",
            "VILA AMÉRICA;Inhumas;2ª TERÇA-FEIRA;N;aUi7rgdfKELvWeUi6;10;;;T",
            "ELDORADO;Inhumas;2ª SEXTA-FEIRA;N;cQuMH8VfQ6hAB9ak8;10;;;T",
            "ITAGUARU;Itaguaru;2º SÁBADO;T;dZpBbPpKxgGyZgYy9;10;;;T",
            "SANTA ROSA;Santa Rosa;2º SÁBADO;T;LXsR8gPeuX97VbsC6;10;;;T",
            "ITAUÇU;Itauçu;3º SÁBADO;T;KiZHuNZ6jQFGLLaj9;10;;;T",
            "ARAÇU;Araçu;3º SÁBADO;T;WLq5AFvPPXZFU1ubA;10;;;T",
            "ANA NERY;Inhumas;4ª QUINTA-FEIRA;N;tQLq6dG3c2kxcWut5;10;;;T",
            "BRAZABRANTES;Brazabrantes;5ª TERÇA-FEIRA;N;jhEdqWi8JcuD8Sy46;10;;;T",
            "ITAGUARI;Itaguari;5º SÁBADO;T;hmkta1jeoTnfJj7RA;10;;;T",
            "ORDALIA;Itauçu;5º SÁBADO;T;AnRSiHpmmBGFzVqo9;10;;;T"
        ];
