        // Dados completos dos ensaios
        const dados = [
            "<B>CENTRAL</B>;Aragoiânia;1º DOMINGO;17:00H;FAkanFsUT93mmLiu8",
            "VILA BRASÍLIA;Aparecida;1º DOMINGO;17:00H;xYJT4GTg7hSCEzDx6",
            "<B>SETOR GARAVELO</B>;Aparecida;1º DOMINGO;17:00H;cbaHom1Dz6uJrsG39",
            "SETOR DOS BANDEIRANTES;Aparecida;1º DOMINGO;17:00H;8NjPZFBb4FvHgnj18",
            "RESIDENCIAL VILAGE GARAVELO;Aparecida;1º DOMINGO;17:00H;d5ArP8Dez9qpoGqt7",
            "JARDIM TIRADENTES 1;Aparecida;1º DOMINGO;17:00H;EqvstVAQsBkc6Ybh8",
            "JARDIM CASA GRANDE;Aparecida;1º DOMINGO;17:00H;N6TzmdWUVKmjq7qU9",
            "BAIRRO INDEPENDÊNCIA;Aparecida;1º DOMINGO;17:00H;d58NBSKruwc735pA9",
            "VL. SÃO JOSÉ;Goiânia;1º DOMINGO;17:00hs;5kdjpLgQreAGofYKA",
            "ST. UNIVERSITÁRIO;Goiânia;1º DOMINGO;17:00hs;f4jkwB9HdBhJMobN6",
            "ST. URIAS MAGALHÃES;Goiânia;1º DOMINGO;17:00hs;fYH4domMCTcszBZc7",
            "ST. NORTE FERROVIÁRIO II;Goiânia;1º DOMINGO;17:00hs;fyt967DQ1EgXkji18",
            "ST. MADRE GERMANA;Goiânia;1º DOMINGO;17:00hs;pLUuFLWU1AqApnx56",
            "ST. ESTRELA DALVA;Goiânia;1º DOMINGO;17:00hs;DJJ1EU8izHd3iVkh6",
            "ST. FAIÇALVILLE;Goiânia;1º DOMINGO;17:00hs;BnQwHq2mhdCuNmsf7",
            "ST. BELA VISTA;Goiânia;1º DOMINGO;17:00hs;6FfuP1QrYMLrrHXm8",
            "ST. COIMBRA;Goiânia;1º DOMINGO;17:00hs;AHA4PNhtdDhWqMP76",
            "ST. ALPHAVILLE II;Goiânia;1º DOMINGO;17:00hs;VJfWLbqyQPxEaRhm6",
            "RES. ITAIPU;Goiânia;1º DOMINGO;17:00hs;meFED6rqGuhwh9pE7",
            "RES. BRISAS DA MATA;Goiânia;1º DOMINGO;17:00hs;MvRbJroWVEVyQyo3A",
            "PQ. TREMENDÃO;Goiânia;1º DOMINGO;17:00hs;g8YtWxosoERd1aRJ6",
            "PQ. INDUSTRIAL JOÃO BRAZ;Goiânia;1º DOMINGO;17:00hs;YuLEdrUSCdYVVmHH9",
            "JD. PRESIDENTE;Goiânia;1º DOMINGO;17:00hs;rfvBKbu67ozUQNta9",
            "JD. NOVA ESPERANÇA;Goiânia;1º DOMINGO;17:00hs;Y1sZAuF7Td5gjHtUA",
            "JD. LIBERDADE;Goiânia;1º DOMINGO;17:00hs;8jnsTy5LySrqKVzP7",
            "JD. GUANABARA;Goiânia;1º DOMINGO;17:00hs;TAjbgKfYSEVyUPVr5",
            "JD. AMÉRICA;Goiânia;1º DOMINGO;17:00hs;aFi4SSMVq3qz5bsh8",
            "<B>GUAPÓ - CENTRAL</B>;Guapó;1º DOMINGO;17:00hs;UmoNQHrabx42qfyM7",
            "<B>ABADIA DE GOIÁS - CENTRAL</B>;Abadia;1º DOMINGO;17:00hs;TgHBjRy7r7cwX2up8",
            "CAROLINA PARQUE;Goiânia;1º DOMINGO;17:00hs;eJzMbXYnWATf43Vy5",
            "PAPILLON PARQUE;Aparecida;1ª SEGUNDA-FEIRA;19:30H;YCroEDoHWJp4mBq59",
            "CIDADE VERA CRUZ II;Aparecida;1ª SEGUNDA-FEIRA;19:30H;fJiiuLUyTgePVdoRA",
            "COLINA AZUL II;Aparecida;1ª SEGUNDA-FEIRA;19:30H;nE1oznfqzcFHZNNv8",
            "SERRA AZUL;Goiânia;1ª SEGUNDA-FEIRA;19:30hs;b6RKsb7ZjbWLZsyeA",
            "RES. RECANTO DO BOSQUE;Goiânia;1ª SEGUNDA-FEIRA;19:30hs;beu4rSFcierdzrTL7",
            "RES. JUNQUEIRA;Goiânia;1ª SEGUNDA-FEIRA;19:30hs;jg68McQ7giL62ba28",
            "JD. MARILIZA;Goiânia;1ª SEGUNDA-FEIRA;19:30hs;k81iAAmHK7dhhftw8",
            "<B>GOIANIRA - CENTRAL</B>;Goianira;1ª SEGUNDA-FEIRA;19:30hs;DaKwLA4yfFB9uvxC8",
            "BAIRRO SÃO CARLOS;Goiânia;1ª SEGUNDA-FEIRA;19:30hs;WrzELsFVxh1oyZJi6",
            "CIDADE JARDIM;Goiânia;1ª TERÇA-FEIRA;19:30hs;h7aTYPFAnBYe6W427",
            "PQ. OESTE INDUSTRIAL;Goiânia;1ª TERÇA-FEIRA;19:30hs;yFEJsMV1oq5Lo7BK8",
            "PQ. ATHENEU;Goiânia;1ª QUARTA-FEIRA;19:30hs;6JJ8NsTNgakSJVTV7",
            "VL. RIZZO;Goiânia;1ª QUINTA-FEIRA;19:30hs;eNNv5dgHFbinBLL47",
            "RES. CENTER VILLE;Goiânia;1ª QUINTA-FEIRA;19:30hs;QfcbSL2by3fQi45TA",
            "JD. STO ANTÔNIO;Goiânia;1ª QUINTA-FEIRA;19:30hs;JBvHtFB7vJAK4aC8A",
            "JD. BALNEÁRIO MEIA PONTE;Goiânia;1ª SEXTA-FEIRA;19:30hs;C5erC5BGabA7aH8H7",
            "PARQUE IBIRAPUERA;Aparecida;1ª SEXTA-FEIRA;19:30H;YBz12uTTvvupg1v16",
            "VARJÃO - FAZ. SALOBRO DE BAIXO;Goiânia;1ª SEXTA-FEIRA;19:30hs;WedDouD7xqsoosXD8",
            "INDEPENDÊNCIA MANSÕES I;Aparecida;1ª SEXTA-FEIRA;19:30H;HB5VegSFgms4WMGj7",
            "RES. MAR DEL PLATA;Goiânia;1ª SEXTA-FEIRA;19:30hs;KL3hP3EnU6FFn7Em6",
            "STO HILÁRIO;Goiânia;1ª SEXTA-FEIRA;19:30hs;ofo9X9vxfmm6zjbo6",
            "JARDIM IPANEMA;Aparecida;1º SÁBADO;17:00H;8gmFtFfCeVx2NvVx7",
            "ST. PERIM;Goiânia;1º SÁBADO;17:00hs;jBCcBz3r4Ko1LF3o7",
            "ST. PALMITO(confirmar);Goiânia;1º SÁBADO;17:00hs;tM3Z2rcm5XthTGLn6",
            "ST. GOIÂNIA VIVA;Goiânia;1º SÁBADO;17:00hs;KdGCYm1SVy7Qxfqc6",
            "RES. MORADA DO IPÊ;Goiânia;1º SÁBADO;17:00hs;GksGsiGsrxWWGYe99",
            "RES. ÍRIS VILLE;Goiânia;1º SÁBADO;17:00hs;VyEhWKcqUz2NdD5U7",
            "REAL CONQUISTA;Goiânia;1º SÁBADO;17:00hs;T3PugKZyNpHAMAg56",
            "PQ. DAS FLORES;Goiânia;1º SÁBADO;17:00hs;MuWhXkmKDwNGgEXh8",
            "CHÁCARA CÉU AZUL;Goiânia;1º SÁBADO;17:00hs;Z6jVPKW89bh8zWHc8",
            "DISTRITO DE NOVA FÁTIMA;Hidrolândia;2º DOMINGO;17:00H;Jitgq66ePpp4BaLK8",
            "SETOR VALE DO SOL;Aparecida;2º DOMINGO;17:00H;zJzwGSJbX4NTYQAe8",
            "SETOR SERRA DOURADA III;Aparecida;2º DOMINGO;17:00H;WYJtMZjDUu5pUgLx7",
            "SETOR MARISTA SUL;Aparecida;2º DOMINGO;17:00H;pJatAUUpBst8VipH8",
            "RESIDENCIAL CARAÍBAS;Aparecida;2º DOMINGO;17:00H;KuwxTZAzTQ57avH67",
            "RESIDENCIAL SANTA LUZIA;Aparecida;2º DOMINGO;17:00H;Hfbyg7kU1orKdBJ8A",
            "ROSA DOS VENTOS;Aparecida;2º DOMINGO;17:00H;t5fpJLTsZcZa7too7",
            "JARDIM DAS CASCATAS;Aparecida;2º DOMINGO;17:00H;c88qH1kAHEnyCLV7A",
            "CIDADE VERA CRUZ I;Aparecida;2º DOMINGO;17:00H;8z925WBJfg1RC2oE6",
            "VL. SANTA HELENA;Goiânia;2º DOMINGO;17:00hs;8bbzMas2TnnVDXNy8",
            "VL. PEDROSO;Goiânia;2º DOMINGO;17:00hs;H7qLWAEgHB1G2udx7",
            "ST. JAÓ;Goiânia;2º DOMINGO;17:00hs;TNb2ePXS5rQuxJx26",
            "ST. NOROESTE;Goiânia;2º DOMINGO;17:00hs;JdMpUusT9jvbXuAY9",
            "ST. FINSOCIAL;Goiânia;2º DOMINGO;17:00hs;LhYD3ZknK7MNH1tXA",
            "ST. ALTO DO VALE;Goiânia;2º DOMINGO;17:00hs;qPrJpePnWe5WCLh6A",
            "JD. POMPÉIA;Goiânia;2º DOMINGO;17:00hs;W3koKo4c4GdPf9VPA",
            "JD. ITAIPU;Goiânia;2º DOMINGO;17:00hs;MQnbKAhq1fcgPSxdA",
            "JD. DAS OLIVEIRAS;Goiânia;2º DOMINGO;17:00hs;kqZLW4r7Qce2jqze9",
            "JD. CURITIBA 3;Goiânia;2º DOMINGO;17:00hs;NPx2UipgVr8f7NtD9",
            "GOIANIRA - CORA CORALINA;Goianira;2º DOMINGO;17:00hs;eJH1spFKgCKxmA6t5",
            "CONJ. VERA CRUZ II;Goiânia;2º DOMINGO;17:00hs;NqdAXaUcVfFszREh8",
            "ABADIA DE GOIÁS - REC DOS DOURADOS;Abadia;2º DOMINGO;17:00hs;mN3ME7NYVVikaa2u5",
            "JARDIM DOS BURITIS;Aparecida;2ª SEGUNDA-FEIRA;19:30H;TayGSqjSSEow244m8",
            "ST. CRIMÉIA LESTE;Goiânia;2ª SEGUNDA-FEIRA;19:30hs;BpjzdrtJ2dDbwLjKA",
            "GOIANIRA - PQ. LOS ANGELES I;Goianira;2ª SEGUNDA-FEIRA;19:30hs;nGUY8PSRHYXz8qJ67",
            "CAPUAVA;Goiânia;2ª SEGUNDA-FEIRA;19:30hs;VSSC4zA2MYhZCbm26",
            "VL. ROSA;Goiânia;2ª TERÇA-FEIRA;19:30hs;1cFS7ezbQ3qPUWDy7",
            "RES. FONTE DAS ÁGUAS 1(confirmar);Goiânia;2ª TERÇA-FEIRA;19:30hs;aVP46SN2a81qnUxz6",
            "FAMA - ST. MARECHAL RONDON;Goiânia;2ª TERÇA-FEIRA;19:30hs;5TyhAmrtwvYnvwfw8",
            "JARDIM ITAPUÃ(confirmar);Aparecida;2ª TERÇA-FEIRA;19:30H;MEfkGCz8dp56TEL79",
            "PARQUE FLAMBOYANT;Aparecida;2ª QUARTA-FEIRA;19:30H;p1cv8v1pXmtsUyiq8",
            "VL. RORIZ - URIAS MAGALHÃES 2;Goiânia;2ª QUARTA-FEIRA;19:30hs;YwXrcBbGEWvqpZb87",
            "ST. SÃO JUDAS TADEU;Goiânia;2ª QUARTA-FEIRA;19:30hs;z7SA5X6QjFSF47D89",
            "ST. SANTA GENOVEVA;Goiânia;2ª QUARTA-FEIRA;19:30hs;uYp9wBLFHeQJf1rWA",
            "JD. NOVO MUNDO;Goiânia;2ª QUARTA-FEIRA;19:30hs;t193qgTKffUqQhDF7",
            "JARDIM PARAÍSO;Aparecida;2ª QUINTA-FEIRA;19:30H;3ur2XR6PRtxYagc3A",
            "JARDIM ALTO PARAÍSO I;Aparecida;2ª QUINTA-FEIRA;19:30H;836KUbCkUmW9m7HAA",
            "RES. RIO VERDE;Goiânia;2ª QUINTA-FEIRA;19:30hs;ABiGL9zxsG7KbcMe7",
            "JD. GOIÁS;Goiânia;2ª QUINTA-FEIRA;19:30hs;BbRcFyWtZLCqiRV16",
            "JD. CARAVELAS;Goiânia;2ª QUINTA-FEIRA;19:30hs;5MavwLrtVk6pbALm8",
            "COND. DAS ESMERALDA;Goiânia;2ª QUINTA-FEIRA;19:30hs;ZPVuUDLGJwsHp6jz5",
            "JARDIM EUROPA;Goiânia;2ª QUINTA-FEIRA;19:30hs;wCXzwnDgT28jsN6B9",
            "SETOR EXPANSUL;Aparecida;2ª SEXTA-FEIRA;19:30H;fo5Eb6Vat9R4oTGe8",
            "PARQUE HAYALA;Aparecida;2ª SEXTA-FEIRA;19:30H;HdfXFEG8f7UbEpTXA",
            "JARDIM DOM BOSCO II;Aparecida;2ª SEXTA-FEIRA;19:30H;SgRsvHqwLqXTX7HV6",
            "ST. GRAJAÚ;Goiânia;2ª SEXTA-FEIRA;19:30hs;Z83wxgptUs3CpVGX6",
            "ST. PEDRO LUDOVICO;Goiânia;2ª SEXTA-FEIRA;19:30hs;SgUPyCuxBkm485Wi7",
            "ST. SANTOS DUMONT;Goiânia;2ª SEXTA-FEIRA;19:30hs;vJXpG8Z6akbmuHwQ9",
            "RES. BUENA VISTA III;Goiânia;2ª SEXTA-FEIRA;19:30hs;fWnMGPmvaCyj5tR78",
            "PQ. AMAZÔNIA;Goiânia;2ª SEXTA-FEIRA;19:30hs;uz5JdYhjKTGDtxNLA",
            "JD. DAS AROEIRAS / VL. CONCÓRDIA;Goiânia;2ª SEXTA-FEIRA;19:30hs;tiL3hV4RD973dsGG6",
            "ELDORADO OESTE;Goiânia;2ª SEXTA-FEIRA;19:30hs;SuHs1ZRmcLgdekz56",
            "BAIRRO GOYÁ;Goiânia;2ª SEXTA-FEIRA;19:30hs;cxht1iptcMjbbXEi6",
            "FAZENDA CACHOEIRINHA;Aragoiânia;2º SÁBADO;17:00H;2c3WhUHpr9oFYQd4A",
            "RES. AMIN CAMARGO;Goiânia;2º SÁBADO;17:00hs;hewReSMKn7jHxEUq5",
            "SETOR TOCANTINS;Aparecida;3º DOMINGO;17:00H;yUevc3XjBBzRxseGA",
            "JARDIM TIRADENTES 2;Aparecida;3º DOMINGO;17:00H;qacwwAKCEdfWEZgH7",
            "JARDIM IRACEMA;Aparecida;3º DOMINGO;17:00H;uwDWmt5RK1qaDWbd9",
            "VL. CRISTINA;Goiânia;3º DOMINGO;17:00hs;oraHscBHqUFGNJ5a8",
            "RES. SOLANGE PARQUE III;Goiânia;3º DOMINGO;17:00hs;grD9H9zX5hc8TJWD8",
            "RES. VALE DOS SONHOS;Goiânia;3º DOMINGO;17:00hs;FEUpPPMPR1k337E27",
            "ST. GENTIL MEIRELES;Goiânia;3º DOMINGO;17:00hs;THhmWwk9CepizSS6A",
            "RES. BARRA VENTO;Goiânia;3º DOMINGO;17:00hs;mDHg64SGZM5z1Rd16",
            "PQ. MARACANÃ;Goiânia;3º DOMINGO;17:00hs;CxBqm41inwY99xPz8",
            "PRIVÊ DAS OLIVEIRAS;Goiânia;3º DOMINGO;17:00hs;DJD9PxZ3N6uWYSvy5",
            "ÁGUA BRANCA;Goiânia;3º DOMINGO;17:00hs;2YothebbxUbFvadD6",
            "BAIRRO FLORESTA;Goiânia;3º DOMINGO;17:00hs;5jMca7ZaDZzQ5ZMc8",
            "VL. JOÃO VAZ;Goiânia;3ª SEGUNDA-FEIRA;19:30hs;Q3j61hDhWYLYythDA",
            "GOIANIRA - JD. DAS PAINEIRAS;Goianira;3ª SEGUNDA-FEIRA;19:30hs;sGNQWhUMzD1vkNSx7",
            "RES. ORLANDO MORAIS;Goiânia;3ª SEGUNDA-FEIRA;19:30hs;erGUcf8GdNsG1cHh9",
            "PQ. ANHANGUERA;Goiânia;3ª TERÇA-FEIRA;19:30hs;Y6jCNpoXMtKf4hrM9",
            "VL. VIANA;Goiânia;3ª QUARTA-FEIRA;19:30hs;Ytm6KEcX6VvFA3sp9",
            "JD. DA LUZ;Goiânia;3ª QUARTA-FEIRA;19:30hs;KDBznngerzpQ34NW8",
            "CHÁCARA MANSÕES DO CAMPUS;Goiânia;3ª QUINTA-FEIRA;19:30hs;oaLJPkjuidTaVXS17",
            "PARQUE SÃO JORGE;Aparecida;3ª QUINTA-FEIRA;19:30H;2YEbMbcrhrDXXVza6",
            "SETOR PONTAL SUL II;Aparecida;3ª SEXTA-FEIRA;19:30H;XX6ErRQMTNx4UQQS9",
            "INDEPENDÊNCIA MANSÕES II;Aparecida;3ª SEXTA-FEIRA;19:30H;gidwYzPgTvZ5b31Y9",
            "<B>VARJÃO - CENTRAL</B>;Goiânia;3ª SEXTA-FEIRA;19:30hs;wePyJHKwj3dns28M7",
            "VL. ITATIAIA;Goiânia;3ª SEXTA-FEIRA;19:30hs;hgVm1kTF3Zv93XtJ7",
            "CRUZEIRO DO SUL;Aparecida;3ª SEXTA-FEIRA;19:30H;iCpCaCbwqBV2vAVG8",
            "RECANTO DAS MINAS GERAIS;Goiânia;3ª SEXTA-FEIRA;19:30hs;E9GE2mEnjtiPRuHA8",
            "RES. CAMPOS DOURADOS;Goiânia;3ª SEXTA-FEIRA;19:30hs;RWjhyBhNg4SVaCrE9",
            "CHÃO DE ESTRELAS;Aragoiânia;3ª SEXTA-FEIRA;19:30H;Z9psCkC3UPfagmZFA",
            "GARAVELO SUL 2;Hidrolândia;3º SÁBADO;17:00H;LoWB7rwcnvpwq5JAA",
            "SÍTIO SANTA LUZIA;Aparecida;4º DOMINGO;17:00H;6D1j23eCkntw7UFA6",
            "JARDIM BOA ESPERANÇA;Aparecida;4º DOMINGO;17:00H;ofG7hB6yQgk9zG6h8",
            "ST. GOIÂNIA II;Goiânia;4º DOMINGO;17:00hs;pkzUdw3q6PgeTebX7",
            "JD. COLORADO;Goiânia;4º DOMINGO;17:00hs;5nuz13naXNwcWoCZ7",
            "JD. CURITIBA 1;Goiânia;4º DOMINGO;17:00hs;q2HGHxpSGALNVxhMA",
            "JD. DOS CERRADOS III;Goiânia;4º DOMINGO;17:00hs;GFbqCarL74kEfejc7",
            "RES. FELICIDADE;Goiânia;4º DOMINGO;17:00hs;6JDkDNa2fx9bwthh8",
            "MANSÕES PARAÍSO;Aparecida;4ª SEGUNDA-FEIRA;19:30H;4dKHXjHzNevLrX538",
            "JARDIM BONANÇA;Aparecida;4ª SEGUNDA-FEIRA;19:30H;rLyFkSvWcfL5TmM1A",
            "JD. BURITI SERENO GARDEN;Aparecida;4ª SEGUNDA-FEIRA;19:30H;TscgNASVCBuEjnBA8",
            "GOIANIRA - RES. TRIUNFO;Goianira;4ª SEGUNDA-FEIRA;19:30hs;99mL3zFYwHzHGNso8",
            "GOIANIRA - ST SUL (JD. IMPERIAL);Goianira;4ª SEGUNDA-FEIRA;19:30hs;w3ahx7ZqUy8KeEAJA",
            "JD. CALIFÓRNIA;Goiânia;4ª QUINTA-FEIRA;19:30hs;PqrrW6zSdiD1RSKs8",
            "RES. PARK SOLAR;Goiânia;4ª SEXTA-FEIRA;19:30hs;sfcXgF2igCY2nsRG6",
            "STA. RITA;Goiânia;4ª SEXTA-FEIRA;19:30hs;GyvMHiMhQvVfo6uC6",
            "DISTRITO DE OLOANA;Hidrolândia;4º SÁBADO;17:00H;Bm6uW1fF3p9qvXsUA",
            "JD. PRIMAVERA;Goiânia;4º SÁBADO;17:00hs;V2PJyKFW5SEewXrf8",
            "VILA DELFIORI;Aparecida;2º SÁBADO meses ÍMPARES;17:00H;7YpA5szLBfYUbNFc9",
            "SETOR MADRE GERMANA I;Aparecida;3º DOMINGO meses FEV MAI AGO NOV;17:00H;BKSiqBPMvngATgkP8",
            "JARDIM DOS IPÊS I;Aparecida;3º DOMINGO meses MAR JUN SET DEZ;17:00H;tXtR21baRaCyFiHG6",
            "JARDIM DOS IPÊS II;Aparecida;3º DOMINGO meses JAN ABR JUL OUT;17:00H;MXJiuPGyAUtKCLaAA",
            "JARDIM DOM BOSCO I;Aparecida;ULT.DOMINGO;17:00H;P5fCZqCEhJQ8iM8B6",
            "JARDIM IPIRANGA;Aparecida;ULT. SEXTA-FEIRA;19:30H;d6PEBRnhFiwiBrPw7",
            "JARDIM HELVÉCIA;Aparecida;3ª SEGUNDA-FEIRA meses PARES;19:30H;vvzTZ4gNRCtqVaU97",
            "GUAPÓ - CIDADE NOVA;Guapó;3ª SEGUNDA-FEIRA MESES PARES;19:30hs;V8nFr4CRJMs78NVc8",
            "GUAPÓ - VL. JOÃO PEDRO;Guapó;3ª SEGUNDA-FEIRA MESES ÍMPARES;19:30hs;GMFbPuVZB5a8cHGG7",
            "CARDOSO II;Aparecida;3ª SEGUNDA-FEIRA meses ÍMPARES;19:30H;HcPzsYCXyMEx3XpQA",
            "RESIDENCIAL VITTA;Hidrolândia;1ª SEGUNDA-FEIRA meses FEV MAI AGO NOV;19:30H;gLXPAYV8PmwvJbiM8",
            "CENTRAL (NAZARÉ);Hidrolândia;1ª SEGUNDA-FEIRA meses MAR JUN SET DEZ;19:30H;o41TdVY6kpwAdJoF8",
            "CHÁCARA SAVANA;Hidrolândia;1ª SEGUNDA-FEIRA meses JAN ABR JUL OUT;19:30H;naghoBxUC2qv6M5e8",
            "CAMPOS DOURADOS;Aragoiânia;1º SÁBADO meses ÍMPARES;17:00H;x3P79L7ZvybRpbyW7",
            "POSSELÂNDIA - CENTRAL;Guapó;2ª SEGUNDA-FEIRA MESES ÍMPARES;19:30hs;Vrxw18rXRe5oeaYT6",
            "PARQUE VEIGA JARDIM II;Aparecida;2ª SEXTA-FEIRA meses ÍMPARES;19:30H;2RgB2GJw237amEYL8",
            "DISTRITO VL. RICA;Goiânia;3ª SEXTA-FEIRA DOS MESES ÍMPARES;19:30hs;kRnnufBAuWN2HiedA",
            "IND. ST. ANTONIO (T. PROMETIDA);Aparecida;2ª SEXTA-FEIRA meses PARES;19:30H;TvaUyyRADcfky5eaA",
            "JARDIM BURITI SERENO I;Aparecida;4ª SEGUNDA-FEIRA meses ÍMPARES;19:30H;Zdk6Tqvsp9oZsavS7",
            "NOVA OLINDA;Aparecida;ÚLT.QUARTA-FEIRA;19:30H;LZcYBBYJ4qhgPJ9U9",
            "SETOR AEROPORTO SUL;Aparecida;ÚLT.DOMINGO;17:00H;kJnN5yAhCJAfm9gd9",
            "SETOR CONTINENTAL;Aparecida;;;wnMvCcxyCGSxrWD89",
            "DISTRITO DE SANTA MARIA;Hidrolândia;;;",
            "JARDIM ALTO PARAÍSO II;Aparecida;;;c8kRiGzwVfpy43yPA"
        ];
